### PR TITLE
Updates following code review and add ability to restrict to certain pages

### PR DESCRIPTION
**Pull request by mattwire**
This adds the ability to only show this if a contribution page / event registration page has the processor on the page.

* Use helper function to get template path
* Support limiting to pages which have specific processors enabled
* Metadata update, add screenshot, release 1.1

### CODE REVIEW

**Comment by jitendrapurohit** [comment]
Thanks @mattwire. This looks great. I've only one concern.

Slightly unsure about the new setting added on the form.  It might get confusing if the processor selected on the settings form is available on the page along with some more processors. Eg -

- User selects paypal pro in the settings form -

image

- Navigate to the contribution page which has multiple payment processor enabled on it Eg - Eway, PP Pro etc.

- If user selects eway and submits the payment, the extra fee is still added to the contribution.

image

Thoughts? @petednz

**Comment by mattwire** [comment]
@jitendrapurohit @petednz Agree with concern.  I've tried to make the text clear. From experience trying to do things with specific processors when multiple are enabled ends up getting complicated so I went for the simple option of leaving enabled if the processor exists. Then you can create separate pages if you don't want it enabled.

**Comment by petednz** [comment]
Is the issue that we need some clearer language where we currently have "If you specify payment processor here ..." that says eg  'if you enable this for a payment processor then the Extra Fee will apply to all payment processors that are enabled on the same contribution/event page"?

**Comment by mattwire** [comment]
image


@petednz @jitendrapurohit I've updated the description to match - I think this is ok now?

**Pull request merged**
